name: Python Security Check
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - run: |
          python -m pip install --upgrade pip
          pip install bandit safety
      - run: bandit -r .
      - run: safety check
